/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import userpages.*;
/**
 *
 * @author SCC Comlab
 */
public class FirstDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FirstDashboard
     */
    public FirstDashboard() {
        initComponents();
    }
   Color navcolor = new Color(102,0,102);
   Color headcolor = new Color(255,102,102);
   Color bodycolor = new Color(0,102,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        userpanel = new javax.swing.JPanel();
        dashlabel = new javax.swing.JLabel();
        dashpane1 = new javax.swing.JPanel();
        dashlabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        navbar.setBackground(new java.awt.Color(102, 102, 102));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userpanel.setBackground(new java.awt.Color(102, 102, 102));
        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpanelMouseExited(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashlabel.setBackground(new java.awt.Color(0, 102, 102));
        dashlabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashlabel.setText("USER");
        dashlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashlabelMouseExited(evt);
            }
        });
        userpanel.add(dashlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, -1));

        navbar.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 160, 50));

        dashpane1.setBackground(new java.awt.Color(102, 102, 102));
        dashpane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpane1MouseExited(evt);
            }
        });
        dashpane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashlabel1.setBackground(new java.awt.Color(0, 102, 102));
        dashlabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashlabel1.setText("DASHBOARD");
        dashlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashlabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashlabel1MouseExited(evt);
            }
        });
        dashpane1.add(dashlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, -1));

        navbar.add(dashpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 50));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 160, 430);

        header.setBackground(new java.awt.Color(0, 102, 102));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("GYM TRACKER");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 340, 30));

        jPanel1.add(header);
        header.setBounds(160, 0, 650, 120);

        maindesktop.setBackground(new java.awt.Color(153, 153, 153));
        maindesktop.setPreferredSize(new java.awt.Dimension(760, 420));
        maindesktop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maindesktopMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop);
        maindesktop.setBounds(160, 120, 650, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void maindesktopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maindesktopMouseEntered
       
    }//GEN-LAST:event_maindesktopMouseEntered

    private void dashlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashlabelMouseEntered
        dashlabel.setBackground(bodycolor);
    }//GEN-LAST:event_dashlabelMouseEntered

    private void dashlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashlabelMouseExited
        dashlabel.setBackground(navcolor);
    }//GEN-LAST:event_dashlabelMouseExited

    private void dashlabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashlabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dashlabel1MouseEntered

    private void dashlabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashlabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dashlabel1MouseExited

    private void dashpane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpane1MouseEntered
        dashpane1.setBackground(bodycolor);
    }//GEN-LAST:event_dashpane1MouseEntered

    private void dashpane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpane1MouseExited
        dashpane1.setBackground(navcolor);
    }//GEN-LAST:event_dashpane1MouseExited

    private void userpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseEntered
        userpanel.setBackground(bodycolor);
    }//GEN-LAST:event_userpanelMouseEntered

    private void userpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseExited
      userpanel.setBackground(navcolor);
    }//GEN-LAST:event_userpanelMouseExited

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
      userpage up = new userpage();
      maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_userpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashlabel;
    private javax.swing.JLabel dashlabel1;
    private javax.swing.JPanel dashpane1;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
